/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"context"
	"os"
	"path"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"

	cozeHandler "github.com/coze-dev/coze-studio/backend/api/handler/coze"
	coze "github.com/coze-dev/coze-studio/backend/api/router/coze"
	"github.com/coze-dev/coze-studio/backend/pkg/logs"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	// INSERT_POINT: DO NOT DELETE THIS LINE!
	coze.Register(r)

	// 注册自定义路由 - 节点推荐系统
	registerRecommendationRoutes(r)

	// 注册 Adapter API 路由
	registerAdapterRoutes(r)

	// 注册 K12 Adapter API 路由
	registerK12AdapterRoutes(r)

	staticFileRegister(r)
}

// staticFileRegister registers web page router.
func staticFileRegister(r *server.Hertz) {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[staticFileRegister] Failed to get current working directory: %v", err)
		cwd = os.Getenv("PWD")
	}

	staticFile := path.Join(cwd, "resources/static/index.html")

	r.Static("/static", path.Join(cwd, "/resources/static"))
	r.StaticFile("/favicon.png", "./resources/static/favicon.png")
	r.StaticFile("/", staticFile)
	r.StaticFile("/sign", staticFile)

	r.StaticFS("/admin", &app.FS{
		Root:               path.Join(cwd, "/resources/conf"),
		GenerateIndexPages: true,
		IndexNames:         []string{"index.html"},
	})

	// r.StaticFS("/admin", &app.FS{
	// 	Root:               path.Join(cwd, "/../backend/conf"),
	// 	GenerateIndexPages: true,
	// 	IndexNames:         []string{"index.html"},
	// })

	type data struct {
		Code int32  `json:"code"`
		Msg  string `json:"msg"`
	}

	r.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.GetRequest().URI().Path())
		if strings.HasPrefix(path, "/api/") ||
			strings.HasPrefix(path, "/v1/") ||
			strings.HasPrefix(path, "/v3/") {
			ctx.JSON(404, data{
				Code: 404,
				Msg:  "not found",
			})
			return
		}

		// index page will show 404 error
		ctx.File(staticFile)
	})

}

// registerRecommendationRoutes 注册节点推荐路由
func registerRecommendationRoutes(r *server.Hertz) {
	nodeAPI := r.Group("/api/workflow_api/node")
	{
		nodeAPI.POST("/recommend", cozeHandler.GetNodeRecommendations)
		nodeAPI.POST("/recommend/feedback", cozeHandler.RecordNodeFeedback)
	}

	// 注册工作流生成路由
	workflowAPI := r.Group("/api/workflow_api")
	{
		workflowAPI.POST("/generate", cozeHandler.GenerateWorkflow)
		workflowAPI.GET("/llm_status", cozeHandler.GetLLMStatus)
	}

	logs.Infof("Workflow API routes registered (node recommendation + workflow generation)")
}

// registerAdapterRoutes 注册 Adapter API 路由
func registerAdapterRoutes(r *server.Hertz) {
	adapterAPI := r.Group("/api/adapter")
	{
		// 适配器管理
		adapterAPI.POST("/register", cozeHandler.RegisterAdapter)
		adapterAPI.GET("/list", cozeHandler.ListAdapters)
		adapterAPI.GET("/:adapter_id", cozeHandler.GetAdapterInfo)

		// 适配器执行
		adapterAPI.POST("/:adapter_id/execute", cozeHandler.ExecuteAdapter)

		// 用户适配器
		adapterAPI.POST("/:adapter_id/install", cozeHandler.InstallAdapter)
		adapterAPI.GET("/installed", cozeHandler.GetInstalledAdapters)
	}

	logs.Infof("Adapter API routes registered")
}

// registerK12AdapterRoutes 注册 K12 Adapter API 路由
func registerK12AdapterRoutes(r *server.Hertz) {
	k12Handler := cozeHandler.NewK12AdapterHandler()

	k12API := r.Group("/api/adapter/k12")
	{
		// 分析用户输入
		k12API.POST("/analyze", k12Handler.AnalyzeInput)

		// 生成学习计划
		k12API.POST("/generate-plan", k12Handler.GenerateLearningPlan)

		// 获取知识点详情
		k12API.GET("/knowledge/:id", k12Handler.GetKnowledgeDetails)

		// 生成习题集
		k12API.POST("/exercises", k12Handler.GenerateExercises)
	}

	logs.Infof("K12 Adapter API routes registered")
}
